export const players = [
  {
    _id: '1',
    playerID: '3333',
    playerName: 'James Milner',
    age: '37',
    position: 'Central Midfield',
    clubId: '44',
    club: 'Brighton & Hove Albion',
    marketValue: '1,50',
    currency: 'm',
    numeral: '€',
    agent: 'CAA Stellar',
  },
  {
    _id: '2',
    playerID: '4444',
    playerName: 'Wojciech Szczesny',
    age: '29',
    position: 'Goalkeeper',
    clubId: '54',
    club: 'Juventus FC',
    marketValue: '10',
    currency: 'm',
    numeral: '€',
    agent: 'CAA Stellar',
  },
];