import { ITeam } from '@/types/leagues';

export const mocks: ITeam[] = [
  {
    id: '1237',
    rank: 1,
    clubName: 'Brighton',
    clubImage: 'https://tmssl.akamaized.net/images/wappen/medium/1237.png?lm=1492718902',
    matches: 1,
    wins: 1,
    draw: 0,
    losses: 0,
    goals: 5,
    goalsConceded: 0,
    group: null,
    goalDifference: 5,
    points: 3,
    markClass: 'fff',
    markColor: 'fff',
    markDescription: 'fff',
    markID: 'fff',
    oldRank: 6,
  },
  {
    id: '281',
    rank: 2,
    clubName: 'Man City',
    clubImage: 'https://tmssl.akamaized.net/images/wappen/medium/281.png?lm=1467356331',
    matches: 1,
    wins: 1,
    draw: 0,
    losses: 0,
    goals: 5,
    goalsConceded: 0,
    group: null,
    goalDifference: 5,
    points: 3,
    markClass: 'fff',
    markColor: 'fff',
    markDescription: 'fff',
    markID: 'fff',
    oldRank: 6,
  },
  {
    id: '11',
    rank: 3,
    clubName: 'Arsenal',
    clubImage: 'https://tmssl.akamaized.net/images/wappen/medium/11.png?lm=1489787850',
    matches: 1,
    wins: 1,
    draw: 0,
    losses: 0,
    goals: 5,
    goalsConceded: 0,
    group: null,
    goalDifference: 5,
    points: 3,
    markClass: 'fff',
    markColor: 'fff',
    markDescription: 'fff',
    markID: 'fff',
    oldRank: 6,
  },
];

export const testt = [
  {
    age: 37,
    dateOfBirth: '04 Jan. 1986',
    flag: 'https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569',
    id: '3333',
    image: 'https://img.a.transfermarkt.technology/portrait/medium/3333-1662621121.jpg?lm=1',
    name: 'James Milner',
    positionFull: 'Central Midfield',
    positionGroup: 'Midfield',
    positionShort: 'CM',
    shirtNumber: '6',
    value: '1,50 m €',
  },
  {
    age: 35,
    dateOfBirth: '10 May 1988',
    flag: 'https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569',
    id: '43530',
    image: 'https://img.a.transfermarkt.technology/portrait/medium/43530-1662663337.jpg?lm=1',
    name: 'Adam La',
    positionFull: 'Central Midfield',
    positionGroup: 'Midfield',
    positionShort: 'CM',
    shirtNumber: '14',
    value: '1,20 m €',
  },
  {
    age: 35,
    dateOfBirth: '10 May 1988',
    flag: 'https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569',
    id: '4330',
    image: 'https://img.a.transfermarkt.technology/portrait/medium/43530-1662663337.jpg?lm=1',
    name: 'Adam Lallana',
    positionFull: 'Attacking Midfield',
    positionGroup: 'Midfield',
    positionShort: 'AM',
    shirtNumber: '14',
    value: '1,20 m €',
  },

  {
    age: 32,
    dateOfBirth: '26 Nov. 1990',
    flag: 'https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569',
    id: '67063',
    image: 'https://img.a.transfermarkt.technology/portrait/medium/67063-1528450601.jpg?lm=1',
    name: 'Danny Welbeck',
    positionFull: 'Centre-Forward',
    positionGroup: 'Midfield',
    positionShort: 'DM',
    shirtNumber: '18',
    value: '7,00 m €',
  },
  {
    age: 32,
    dateOfBirth: '26 Nov. 1990',
    flag: 'https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569',
    id: '6706',
    image: 'https://img.a.transfermarkt.technology/portrait/medium/67063-1528450601.jpg?lm=1',
    name: 'John Week',
    positionFull: 'Centre-Forward',
    positionGroup: 'Goalkeeper',
    positionShort: 'CF',
    shirtNumber: '18',
    value: '7,00 m €',
  },
];