export const trhist = [
  {
    playerID: '340329',
    oldClubID: '9249',
    oldClubName: 'Arsenal U23',
    oldClubImage: 'https://tmssl.akamaized.net/images/wappen/medium/9249.png?lm=1489787850',
    newClubID: '11',
    newClubName: 'Arsenal',
    newClubImage: 'https://tmssl.akamaized.net/images/wappen/medium/11.png?lm=1489787850',
    feeValue: '17,00',
    feeCurrency: '€',
    feeNumeral: 'm',
    loan: '',
    date: 'Jul 1, 2019',
    season: '19/20',
  },
  {
    playerID: '340329',
    oldClubID: '11',
    oldClubName: 'Arsenal',
    oldClubImage: 'https://tmssl.akamaized.net/images/wappen/medium/11.png?lm=1489787850',
    newClubID: '762',
    newClubName: 'Newcastle',
    newClubImage: 'https://tmssl.akamaized.net/images/wappen/medium/762.png?lm=1472921161',
    feeValue: '?',
    feeCurrency: '',
    feeNumeral: '',
    loan: 'ist',
    date: 'Feb 1, 2021',
    season: '20/21',
  },
];

export const valueM = [
  {
    date: '20 Jun 2023',
    age: '23',
    marketValue: '17,00',
    mValueUnform: 17000000,
    mValueCurr: '€',
    mValueNum: 'm',
    clubName: 'Newcastle United',
  },
  {
    date: '03 Nov 2022',
    age: '23',
    marketValue: '30,00',
    mValueUnform: 30000000,
    mValueCurr: '€',
    mValueNum: 'm',
    clubName: 'Newcastle United',
  },
  {
    date: '15 Sep 2022',
    age: '23',
    marketValue: '25,00',
    mValueUnform: 25000000,
    mValueCurr: '€',
    mValueNum: 'm',
    clubName: 'Newcastle United',
  },
  {
    date: '15 Mar 2022',
    age: '23',
    marketValue: '47,00',
    mValueUnform: 47000000,
    mValueCurr: '€',
    mValueNum: 'm',
    clubName: 'Newcastle United',
  },
];

export const test = {
  playerID: '3333',
  playerImage: 'https://img.a.transfermarkt.technology/portrait/medium/3333-1662621121.jpg?lm=1',
  playerName: 'Trent Alexander-Arnold',
  dateOfBirth: 'Jan 4, 1986',
  playerShirtNumber: '6',
  age: '37',
  height: '1,75',
  foot: 'right',
  country: 'England',
  countryImage: 'https://tmssl.akamaized.net/images/flagge/verysmall/189.png?lm=1520611569',
  internationalGames: '61',
  internationalGoals: '1',
  league: 'Premier League',
  leagueLogo: 'https://tmssl.akamaized.net/images/logo/normal/gb1.png?lm=1521104656',
  clubImage: 'https://tmssl.akamaized.net/images/wappen/medium/1237.png?lm=1492718902',
  club: 'Brighton & Hove Albion',
  loanUntil: 'Jun 30, 2024',
  LoanOwnerName: 'Chelsea FC',
  ownerImage: 'https://tmssl.akamaized.net/images/wappen/medium/631.png?lm=1682435911',
  contractExpiryDate: 'Jun 30, 2024',
  agent: 'Sports360 GmbH',
  agentId: '199',
  playerMainPosition: 'Central Midfield',
  playerSecondPosition: 'Left Midfield',
  playerThirdPosition: 'Right Midfield',
  marketValue: '127,50',
  marketValueNumeral: 'm',
  marketValueCurrency: '€',
  injuryTitle: 'Hamstring Injury',
  injuryUntil: 'Jan 4, 2024',
};

export const testStats = [
  {
    compId: 'NL1',
    compName: 'Eredivisie',
    compImage: 'https://tmssl.akamaized.net/images/logo/normal/nl1.png?lm=1629726381',
    yellowCards: '3',
    redCards: '0',
    minutesPlayed: 1435,
    penaltyGoals: '0',
    minutesPerGoal: 717.5,
    matches: '19',
    goals: '2',
    assists: '2',
    toNil: 8,
    concededGoals: 4,
    isGoalkeeper: null,
  },
  {
    compId: 'CGB',
    compName: 'EFL Cup',
    compImage: 'https://tmssl.akamaized.net/images/logo/normal/cgb.png?lm=1566937342',
    yellowCards: '6',
    redCards: '0',
    minutesPlayed: 1435,
    penaltyGoals: '0',
    minutesPerGoal: 717.5,
    matches: '8',
    goals: '4',
    assists: '2',
    toNil: 4,
    concededGoals: 2,
    isGoalkeeper: true,
  },
];
